<?php

namespace Database\Seeders;

use App\Models\Moviles;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MovilesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E15'; $m->chapa = 'BZF664'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E10'; $m->chapa = 'HCB613'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J21'; $m->chapa = 'HGC221'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J50'; $m->chapa = 'AABF855'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '750'; $m->chapa = 'AAHX638'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J05'; $m->chapa = 'HFB439'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J02'; $m->chapa = 'HFB412'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X36'; $m->chapa = 'HCE180'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X37'; $m->chapa = 'BPB620'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J14'; $m->chapa = 'HGC154'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J04'; $m->chapa = 'HFB442'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '756'; $m->chapa = 'AAIB362'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '627'; $m->chapa = 'XAF036'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J18'; $m->chapa = 'HGC163'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '736'; $m->chapa = 'AAHU179'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '742'; $m->chapa = 'AAHB038'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '758'; $m->chapa = 'AAIN587'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '735'; $m->chapa = 'AAHS273'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J26'; $m->chapa = 'HGB496'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J35'; $m->chapa = 'AABF847'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J03'; $m->chapa = 'HFB416'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '746'; $m->chapa = 'AAHX623'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J49'; $m->chapa = 'AABF874'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J48'; $m->chapa = 'AABF881'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E20'; $m->chapa = 'HDC329'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J31'; $m->chapa = 'AABF839'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J42'; $m->chapa = 'AABF850'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J46'; $m->chapa = 'AABF879'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E35'; $m->chapa = 'AAAZ994'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '715'; $m->chapa = 'AACD894'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E17'; $m->chapa = 'HBJ458'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E40'; $m->chapa = 'AAEP592'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J58'; $m->chapa = 'AABF862'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J32'; $m->chapa = 'AABF844'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '927'; $m->chapa = 'BVP941'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '739'; $m->chapa = 'AAHZ841'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J07'; $m->chapa = 'HFB436'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X20'; $m->chapa = 'HEJ272'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J37'; $m->chapa = 'AABF848'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E24'; $m->chapa = 'AAAZ987'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X18'; $m->chapa = 'HBK468'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '755'; $m->chapa = 'AAIB364'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J55'; $m->chapa = 'AABF859'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J51'; $m->chapa = 'AABF856'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J22'; $m->chapa = 'HGC230'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J16'; $m->chapa = 'HGC160'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '754'; $m->chapa = 'AAHX976'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X13'; $m->chapa = 'BPB623'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J59'; $m->chapa = 'AABF861'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J53'; $m->chapa = 'AABF883'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J47'; $m->chapa = 'AABF877'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X19'; $m->chapa = 'HEJ269'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '988'; $m->chapa = 'BYC171'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '660'; $m->chapa = 'XBF037'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E11'; $m->chapa = 'HCB609'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J54'; $m->chapa = 'AABF858'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E28'; $m->chapa = 'AAAZ989'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J13'; $m->chapa = 'HGC156'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '215'; $m->chapa = 'BHZ416'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X28'; $m->chapa = 'AABO726'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '753'; $m->chapa = 'AAHX642'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J19'; $m->chapa = 'HGC168'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J06'; $m->chapa = 'HFB433'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J29'; $m->chapa = 'HGB499'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E13'; $m->chapa = 'BZF666'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E36'; $m->chapa = 'AAEP594'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E32'; $m->chapa = 'AAAZ992'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J15'; $m->chapa = 'HGC222'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'W14'; $m->chapa = 'BVG773'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J11'; $m->chapa = 'HFF746'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '738'; $m->chapa = 'AAGG912'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '221'; $m->chapa = 'YAJ704'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E34'; $m->chapa = 'AAAZ993'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E03'; $m->chapa = 'AADC290'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E30'; $m->chapa = 'AAAZ991'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '218'; $m->chapa = 'HGJ265'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E05'; $m->chapa = 'HED274'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J38'; $m->chapa = 'AABF853'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '737'; $m->chapa = 'AAGG910'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '731'; $m->chapa = 'AAHS270'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E12'; $m->chapa = 'HDK527'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '973'; $m->chapa = 'AAIB298'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J25'; $m->chapa = 'HGB503'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J08'; $m->chapa = 'HFB430'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '219'; $m->chapa = 'BNP679'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E08'; $m->chapa = 'BZF667'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '745'; $m->chapa = 'AAHB037'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E04'; $m->chapa = 'HED275'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '868'; $m->chapa = 'AADL875'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '747'; $m->chapa = 'AAHX628'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J30'; $m->chapa = 'HGB490'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X30'; $m->chapa = 'BCF827'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J01'; $m->chapa = 'HFB450'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J17'; $m->chapa = 'HGC224'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E38'; $m->chapa = 'AAEP598'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E23'; $m->chapa = 'AAAZ983'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J24'; $m->chapa = 'HGB507'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J39'; $m->chapa = 'AABF852'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X22'; $m->chapa = 'HGH258'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '740'; $m->chapa = 'AAHB041'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E06'; $m->chapa = 'AADR525'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J41'; $m->chapa = 'AABF866'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '802'; $m->chapa = 'AABT986'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J20'; $m->chapa = 'HGC227'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '655'; $m->chapa = 'XBE988'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X12'; $m->chapa = 'CDV953'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '734'; $m->chapa = 'AAHS281'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J27'; $m->chapa = 'HGB505'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J23'; $m->chapa = 'HGB500'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'L06'; $m->chapa = 'BYS281'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '741'; $m->chapa = 'AAHB040'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J36'; $m->chapa = 'AABF840'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E27'; $m->chapa = 'AAAZ986'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '733'; $m->chapa = 'AAHS276'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E41'; $m->chapa = 'AAEP595'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J43'; $m->chapa = 'AABF869'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '717'; $m->chapa = 'BEZ876'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E26'; $m->chapa = 'AAAZ984'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '713'; $m->chapa = 'AADO517'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J52'; $m->chapa = 'AABF865'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '628'; $m->chapa = 'YAU774'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J45'; $m->chapa = 'AABF867'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E02'; $m->chapa = 'HGL885'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E29'; $m->chapa = 'AAAZ990'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E37'; $m->chapa = 'AAEP608'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J57'; $m->chapa = 'AABF863'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J09'; $m->chapa = 'HFB420'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X38'; $m->chapa = 'CFO951'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J60'; $m->chapa = 'AABF860'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '732'; $m->chapa = 'AAHS280'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J33'; $m->chapa = 'AABF846'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '968'; $m->chapa = 'CFZ254'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '987'; $m->chapa = 'BGP216'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X16'; $m->chapa = 'CFJ284'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X23'; $m->chapa = 'BEZ371'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '716'; $m->chapa = 'AADO518'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X39'; $m->chapa = 'HEV161'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E07'; $m->chapa = 'AABR522'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '749'; $m->chapa = 'AAHX634'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J34'; $m->chapa = 'AABF842'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X08'; $m->chapa = 'HER026'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '804'; $m->chapa = 'AAAI564'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '928'; $m->chapa = 'AXS503'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '966'; $m->chapa = 'CFN218'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '759'; $m->chapa = 'AAIN589'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E25'; $m->chapa = 'AAAZ985'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '730'; $m->chapa = 'AAHS282'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '805'; $m->chapa = 'AAEJ324'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J12'; $m->chapa = 'BVV132'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '757'; $m->chapa = 'AAIN591'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '728'; $m->chapa = 'HAF776'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '967'; $m->chapa = 'CGC206'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J28'; $m->chapa = 'HGB493'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J56'; $m->chapa = 'AABF857'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '702'; $m->chapa = 'AAAG916'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '752'; $m->chapa = 'AAHX641'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X29'; $m->chapa = 'AABO723'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'X24'; $m->chapa = 'HGH262'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '743'; $m->chapa = 'AAHB043'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E33'; $m->chapa = 'AAAZ995'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '748'; $m->chapa = 'AAHX633'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'L03'; $m->chapa = 'AACC867'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E01'; $m->chapa = 'HGL889'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J10'; $m->chapa = 'HFB426'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J40'; $m->chapa = 'AABF864'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E31'; $m->chapa = 'AAAZ988'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E39'; $m->chapa = 'AAEP593'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '751'; $m->chapa = 'AAHX640'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'J44'; $m->chapa = 'AABF870'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '744'; $m->chapa = 'AAHB042'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '658'; $m->chapa = 'XBE994'; $m->save();
        $m = new Moviles(); $m->tiers_id = 2; $m->nombre = 'E09'; $m->chapa = 'BZP758'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '625'; $m->chapa = 'BVC095'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '881'; $m->chapa = 'AAFF660'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '216'; $m->chapa = 'BJC291'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '624'; $m->chapa = 'BTY058'; $m->save();
        $m = new Moviles(); $m->tiers_id = 1; $m->nombre = '654'; $m->chapa = 'XBE984'; $m->save();
    }
}
