services:
  app:
    container_name: app-cerveparV2
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database
      - web
    networks:
      - shared-net
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-cerveparV2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=cerveparV2
  web:
    container_name: nginx-cerveparV2
    build:
      context: .
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:80
    networks:
      - shared-net
  database:
    container_name: postgres-cerveparV2
    image: postgres:alpine
    volumes:
      - postgres_volumen:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cerveparV2
    ports:
      - 5555:5432
    networks:
      - shared-net

volumes:
  postgres_volumen:

networks:
  shared-net:
    driver: bridge